### ISSUE TITLE
Finish To-Do's (in app files to-do tree) to get cli vite-ssg/vue-ts installations DRYer

### ISSUE THREAD

**Issue by oberocks** [obewds/vueventus#147]
...  and with the minimum needed files - preferring to use generation methods over files duped in both `./cli/stubs/vite-ssg` and `./cli/stubs/vue-ts` directories.

- [x] ./cli/helpers/generateHelloVueVentusTestJsFile.mjs
- [x] ./cli/helpers/generateHelloVueVentusVueFile.mjs
- [x] ./cli/helpers/generateIndexHtmlFile.mjs
- [x] ./cli/helpers/generateVitestConfigTsFile.mjs
- [x] ./cli/helpers/generateVvAnchorVueFile.mjs
- [x] ./cli/helpers/generateVvButtonVueFile.mjs
- [x] ./cli/helpers/generateVvColorModeButtonVueFile.mjs
- [x] ./cli/helpers/generateVvElVueFile.mjs
- [x] ./cli/helpers/generateVvInputVueFile.mjs
- [x] ./cli/helpers/generateVvListItemVueFile.mjs
- [x] ./cli/helpers/generateVvPrismVueFile.mjs
- [x] ./cli/helpers/generateVvScrollUpVueFile.mjs
- [x] ./cli/helpers/generateVvTextareaVueFile.mjs
- [x] ./cli/helpers/generateVvTsConfigJsonFile.mjs
